import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  ar: {
    // Layout & Navigation
    dashboards: 'لوحات التحكم',
    dashboard: 'لوحة التحكم',
      centralDashboard: 'لوحة مركزية',
    maps: 'الخرائط',
    waste: 'النفايات',
    operations: 'العمليات',
    fleet: 'الأسطول',
    iot: 'أجهزة IoT',
    procurement: 'المخزون',
    iam: 'المستخدمين',
    security: 'الأمن',
    reports: 'التقارير',
    communication: 'الاتصالات',
    devices: 'الأجهزة',
    incidentCenter: 'مركز الحوادث',
    ai: 'الذكاء الاصطناعي',
    resourceManagement: 'إدارة الموارد',
    aiNotifications: 'إعدادات إشعارات AI',
    aiCapabilities: 'قدرات AI',
    aiTraining: 'تدريب AI',
    dataAnalytics: 'تحليل البيانات',
    aiInsights: 'رؤى AI',
    smartHome: 'المنزل الذكي',
    cameraAnalytics: 'تحليلات الكاميرات',
    analyticsBuilder: 'منشئ التحليلات',
    cameraProtocols: 'بروتوكولات الكاميرا',
    integrations: 'التكاملات',
    clients: 'العملاء',
    notifications: 'الإشعارات',
    modules: 'الوحدات',
    solutionTemplates: 'قوالب الحلول',
    widgetsLibrary: 'مكتبة الأدوات',
    ruleChains: 'سلاسل القواعد',
    whiteLabeling: 'العلامة البيضاء',
    dashboardBuilder: 'منشئ لوحة التحكم',
    userManagement: 'إدارة المستخدمين',
    adminAssistant: 'مساعد المدير',
    aiModels: 'نماذج AI',
    forensicHub: 'مركز التحقيق',
    smartCityMap: 'خريطة المدينة الذكية',
    droneFusion: 'دمج الدرونز',
    cameraHealth: 'صحة الكاميرات',
    trafficIntelligence: 'ذكاء المرور',
    fleetTelematics: 'تتبع الأسطول',
    cybersecurity: 'الأمن السيبراني',
    aiAssistant: 'مساعد AI',
    settings: 'الإعدادات',
    advancedSettings: 'إعدادات متقدمة',
    profile: 'الملف الشخصي',
    assetManagement: 'إدارة الأصول',
    indoorTracking: 'التتبع الداخلي',
    fuelManagement: 'إدارة الوقود',
    hospitalCommand: 'مركز قيادة المستشفى',
    smartCityBrain: 'عقل المدينة الذكي',
    smartTraffic: 'المرور الذكي',
    smartUtilities: 'المرافق الذكية',
    smartEnvironment: 'البيئة الذكية',
    smartGovernance: 'الحوكمة الذكية',
    smartSafety: 'السلامة العامة',
    smartEducation: 'التعليم الذكي',
    smartCommerce: 'التجارة الذكية',
    smartIndustrial: 'المناطق الصناعية',
    smartEnergy: 'شبكة الطاقة',
    cityTwin: 'التوأم الرقمي',
    smartCity: 'المدينة الذكية',
    aiVision: 'AI Vision Hub',
    advancedPreferences: 'التفضيلات المتقدمة',
    generalSettings: 'الإعدادات العامة',
    assets: 'الأصول',
    documentManagement: 'إدارة المستندات',
    notificationCenter: 'مركز الإشعارات',
    interfaceSettings: 'إعدادات الواجهة',
        developerPortal: 'بوابة المطورين',
        systemConfig: 'إعدادات النظام',
        towerManagement: 'إدارة الأبراج',
        unifiedMap: 'الخريطة الموحدة',
        customDashboard: 'لوحة مخصصة',
          logout: 'تسجيل الخروج',
    visitors: 'إدارة الزوار والتصاريح',
    auditLog: 'سجل التدقيق',
    reportBuilder: 'منشئ التقارير',
    maintenance: 'الصيانة',
    inventory: 'المخزون',
    contractors: 'المتعاقدون',
    supplierManagement: 'إدارة الموردين',
    vehicleManagement: 'إدارة المركبات',
    technicianScheduling: 'جدولة الفنيين',
    technicianMobile: 'تطبيق الفني',
    advancedReports: 'التقارير المتقدمة',
      reportsDashboard: 'لوحة التقارير',
      roleManagement: 'إدارة الأدوار',
    callCenter: 'مركز الاتصال',
    smartCity: 'المدينة الذكية',
    wasteManagement: 'إدارة النفايات',
    citizenWasteReports: 'بلاغات المواطنين',
    smartRouting: 'المسارات الذكية',
    communicationHub: 'مركز التواصل',
    complianceCenter: 'مركز الامتثال',
    commandCenter: 'مركز القيادة',
    fleetAdvanced: 'الأسطول المتقدم',
    hrWorkforce: 'القوى العاملة',
    deviceConfig: 'إعدادات الأجهزة',
    unifiedCallCenter: 'مركز الاتصال المتقدم',
    advancedCallCenter: 'مركز AI المتكامل',
    enhancedSettings: 'الإعدادات المتقدمة',
    resourceAllocation: 'تخصيص الموارد',
    visitorPortal: 'بوابة الزوار',
    reportsCenter: 'مركز التقارير',
    aiReports: 'تقارير AI',

    // Common
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    add: 'إضافة',
    search: 'بحث',
    filter: 'تصفية',
    export: 'تصدير',
    import: 'استيراد',
    refresh: 'تحديث',
    loading: 'جاري التحميل...',
    noData: 'لا توجد بيانات',
    success: 'تم بنجاح',
    error: 'خطأ',
    warning: 'تحذير',
    info: 'معلومات',
    confirm: 'تأكيد',
    close: 'إغلاق',
    
    // Solution Templates
    solutionTemplatesTitle: 'قوالب الحلول الجاهزة',
    solutionTemplatesDesc: 'حلول متكاملة لمختلف القطاعات',
    allCategories: 'جميع الفئات',
    security: 'الأمن',
    traffic: 'المرور',
    retail: 'التجزئة',
    industrial: 'الصناعة',
    healthcare: 'الرعاية الصحية',
    education: 'التعليم',
    preview: 'معاينة',
    deploy: 'نشر',
    features: 'الميزات',
    requirements: 'المتطلبات',
    
    // Language
    language: 'اللغة',
    arabic: 'العربية',
    english: 'English',
    french: 'Français',
    spanish: 'Español',
    chinese: '中文',
    selectLanguage: 'اختر اللغة',
  },
  en: {
    // Layout & Navigation
    dashboards: 'Dashboards',
    dashboard: 'Dashboard',
      centralDashboard: 'Central Dashboard',
    maps: 'Maps',
    waste: 'Waste',
    operations: 'Operations',
    fleet: 'Fleet',
    iot: 'IoT Devices',
    procurement: 'Procurement',
    iam: 'Users & Access',
    security: 'Security',
    reports: 'Reports',
    communication: 'Communications',
    devices: 'Devices',
    incidentCenter: 'Incident Center',
    ai: 'Artificial Intelligence',
    resourceManagement: 'Resource Management',
    aiNotifications: 'AI Notification Settings',
    aiCapabilities: 'AI Capabilities',
    aiTraining: 'AI Training',
    dataAnalytics: 'Data Analytics',
    aiInsights: 'AI Insights',
    smartHome: 'Smart Home',
    cameraAnalytics: 'Camera Analytics',
    analyticsBuilder: 'Analytics Builder',
    cameraProtocols: 'Camera Protocols',
    integrations: 'Integrations',
    clients: 'Clients',
    notifications: 'Notifications',
    modules: 'Modules',
    solutionTemplates: 'Solution Templates',
    widgetsLibrary: 'Widgets Library',
    ruleChains: 'Rule Chains',
    whiteLabeling: 'White Labeling',
    dashboardBuilder: 'Dashboard Builder',
    userManagement: 'User Management',
    adminAssistant: 'Admin Assistant',
    aiModels: 'AI Models',
    forensicHub: 'Forensic Hub',
    smartCityMap: 'Smart City Map',
    droneFusion: 'Drone Fusion',
    cameraHealth: 'Camera Health',
    trafficIntelligence: 'Traffic Intelligence',
    fleetTelematics: 'Fleet / Telematics',
    cybersecurity: 'Cybersecurity',
    aiAssistant: 'AI Assistant',
    settings: 'Settings',
    advancedSettings: 'Advanced Settings',
    profile: 'Profile',
    assetManagement: 'Asset Management',
    indoorTracking: 'Indoor Tracking',
    fuelManagement: 'Fuel Management',
    hospitalCommand: 'Hospital Command',
    smartCityBrain: 'Smart City Brain',
    smartTraffic: 'Smart Traffic',
    smartUtilities: 'Smart Utilities',
    smartEnvironment: 'Smart Environment',
    smartGovernance: 'Smart Governance',
    smartSafety: 'Public Safety',
    smartEducation: 'Smart Education',
    smartCommerce: 'Smart Commerce',
    smartIndustrial: 'Smart Industrial',
    smartEnergy: 'Smart Energy',
    cityTwin: 'Digital Twin',
    smartCity: 'Smart City',
    aiVision: 'AI Vision Hub',
    advancedPreferences: 'Advanced Preferences',
    generalSettings: 'General Settings',
    assets: 'Assets',
    documentManagement: 'Document Management',
    notificationCenter: 'Notification Center',
    interfaceSettings: 'Interface Settings',
        developerPortal: 'Developer Portal',
        systemConfig: 'System Config',
        towerManagement: 'Tower Management',
        unifiedMap: 'Unified Map',
        customDashboard: 'Custom Dashboard',
          logout: 'Logout',
    visitors: 'Visitors & Permits',
    auditLog: 'Audit Log',
    reportBuilder: 'Report Builder',
    maintenance: 'Maintenance',
    inventory: 'Inventory',
    contractors: 'Contractors',
    supplierManagement: 'Supplier Management',
    vehicleManagement: 'Vehicle Management',
    technicianScheduling: 'Technician Scheduling',
    technicianMobile: 'Technician App',
    advancedReports: 'Advanced Reports',
      reportsDashboard: 'Reports Dashboard',
      roleManagement: 'Role Management',
    callCenter: 'Call Center',
    smartCity: 'Smart City',
    wasteManagement: 'Waste Management',
    citizenWasteReports: 'Citizen Waste Reports',
    smartRouting: 'Smart Routing',
    communicationHub: 'Communication Hub',
    complianceCenter: 'Compliance Center',
    commandCenter: 'Command Center',
    fleetAdvanced: 'Fleet Advanced',
    hrWorkforce: 'HR Workforce',
    deviceConfig: 'Device Config',
    unifiedCallCenter: 'Unified Call Center',
    advancedCallCenter: 'Advanced AI Call Center',
    enhancedSettings: 'Enhanced Settings',
    resourceAllocation: 'Resource Allocation',
    visitorPortal: 'Visitor Portal',
    reportsCenter: 'Reports Center',
    aiReports: 'AI Reports',

    // Common
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    import: 'Import',
    refresh: 'Refresh',
    loading: 'Loading...',
    noData: 'No Data',
    success: 'Success',
    error: 'Error',
    warning: 'Warning',
    info: 'Info',
    confirm: 'Confirm',
    close: 'Close',
    
    // Solution Templates
    solutionTemplatesTitle: 'Ready Solution Templates',
    solutionTemplatesDesc: 'Integrated solutions for various sectors',
    allCategories: 'All Categories',
    security: 'Security',
    traffic: 'Traffic',
    retail: 'Retail',
    industrial: 'Industrial',
    healthcare: 'Healthcare',
    education: 'Education',
    preview: 'Preview',
    deploy: 'Deploy',
    features: 'Features',
    requirements: 'Requirements',
    
    // Language
    language: 'Language',
    arabic: 'العربية',
    english: 'English',
    french: 'Français',
    spanish: 'Español',
    chinese: '中文',
    selectLanguage: 'Select Language',
  },
  fr: {
    // Layout & Navigation
    dashboard: 'Tableau de bord',
    devices: 'Appareils',
    incidentCenter: 'Centre des incidents',
    aiCapabilities: 'Capacités IA',
    aiTraining: 'Formation IA',
    dataAnalytics: 'Analyse de données',
    aiInsights: 'Aperçus IA',
    smartHome: 'Maison intelligente',
    analyticsBuilder: 'Constructeur d\'analyses',
    cameraProtocols: 'Protocoles caméra',
    integrations: 'Intégrations',
    clients: 'Clients',
    notifications: 'Notifications',
    modules: 'Modules',
    solutionTemplates: 'Modèles de solutions',
    widgetsLibrary: 'Bibliothèque de widgets',
    ruleChains: 'Chaînes de règles',
    whiteLabeling: 'Marque blanche',
    dashboardBuilder: 'Constructeur de tableau de bord',
    userManagement: 'Gestion des utilisateurs',
    aiModels: 'Modèles IA',
    forensicHub: 'Centre forensique',
    smartCityMap: 'Carte ville intelligente',
    droneFusion: 'Fusion drones',
    cameraHealth: 'Santé caméras',
    trafficIntelligence: 'Intelligence trafic',
    fleetTelematics: 'Flotte / Télématique',
    cybersecurity: 'Cybersécurité',
    aiAssistant: 'Assistant IA',
    settings: 'Paramètres',
    profile: 'Profil',
    logout: 'Déconnexion',
    
    // Common
    save: 'Enregistrer',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    add: 'Ajouter',
    search: 'Rechercher',
    filter: 'Filtrer',
    export: 'Exporter',
    import: 'Importer',
    refresh: 'Actualiser',
    loading: 'Chargement...',
    noData: 'Aucune donnée',
    success: 'Succès',
    error: 'Erreur',
    warning: 'Avertissement',
    info: 'Info',
    confirm: 'Confirmer',
    close: 'Fermer',
    
    // Solution Templates
    solutionTemplatesTitle: 'Modèles de solutions prêts',
    solutionTemplatesDesc: 'Solutions intégrées pour divers secteurs',
    allCategories: 'Toutes catégories',
    security: 'Sécurité',
    traffic: 'Trafic',
    retail: 'Commerce',
    industrial: 'Industrie',
    healthcare: 'Santé',
    education: 'Éducation',
    preview: 'Aperçu',
    deploy: 'Déployer',
    features: 'Fonctionnalités',
    requirements: 'Exigences',
    
    // Language
    language: 'Langue',
    arabic: 'العربية',
    english: 'English',
    french: 'Français',
    spanish: 'Español',
    chinese: '中文',
    selectLanguage: 'Sélectionner la langue',
  },
  es: {
    // Layout & Navigation
    dashboard: 'Panel de control',
    devices: 'Dispositivos',
    incidentCenter: 'Centro de incidentes',
    aiCapabilities: 'Capacidades IA',
    aiTraining: 'Entrenamiento IA',
    dataAnalytics: 'Análisis de datos',
    aiInsights: 'Perspectivas IA',
    smartHome: 'Casa inteligente',
    analyticsBuilder: 'Constructor de análisis',
    cameraProtocols: 'Protocolos de cámara',
    integrations: 'Integraciones',
    clients: 'Clientes',
    notifications: 'Notificaciones',
    modules: 'Módulos',
    solutionTemplates: 'Plantillas de soluciones',
    widgetsLibrary: 'Biblioteca de widgets',
    ruleChains: 'Cadenas de reglas',
    whiteLabeling: 'Marca blanca',
    dashboardBuilder: 'Constructor de panel',
    userManagement: 'Gestión de usuarios',
    aiModels: 'Modelos IA',
    forensicHub: 'Centro forense',
    smartCityMap: 'Mapa ciudad inteligente',
    droneFusion: 'Fusión de drones',
    cameraHealth: 'Salud de cámaras',
    trafficIntelligence: 'Inteligencia de tráfico',
    fleetTelematics: 'Flota / Telemática',
    cybersecurity: 'Ciberseguridad',
    aiAssistant: 'Asistente IA',
    settings: 'Configuración',
    profile: 'Perfil',
    logout: 'Cerrar sesión',
    
    // Common
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    add: 'Añadir',
    search: 'Buscar',
    filter: 'Filtrar',
    export: 'Exportar',
    import: 'Importar',
    refresh: 'Actualizar',
    loading: 'Cargando...',
    noData: 'Sin datos',
    success: 'Éxito',
    error: 'Error',
    warning: 'Advertencia',
    info: 'Info',
    confirm: 'Confirmar',
    close: 'Cerrar',
    
    // Solution Templates
    solutionTemplatesTitle: 'Plantillas de soluciones listas',
    solutionTemplatesDesc: 'Soluciones integradas para varios sectores',
    allCategories: 'Todas las categorías',
    security: 'Seguridad',
    traffic: 'Tráfico',
    retail: 'Comercio',
    industrial: 'Industrial',
    healthcare: 'Salud',
    education: 'Educación',
    preview: 'Vista previa',
    deploy: 'Desplegar',
    features: 'Características',
    requirements: 'Requisitos',
    
    // Language
    language: 'Idioma',
    arabic: 'العربية',
    english: 'English',
    french: 'Français',
    spanish: 'Español',
    chinese: '中文',
    selectLanguage: 'Seleccionar idioma',
  },
  zh: {
    // Layout & Navigation
    dashboard: '仪表板',
    devices: '设备',
    incidentCenter: '事件中心',
    aiCapabilities: 'AI能力',
    aiTraining: 'AI训练',
    dataAnalytics: '数据分析',
    aiInsights: 'AI洞察',
    smartHome: '智能家居',
    analyticsBuilder: '分析构建器',
    cameraProtocols: '摄像头协议',
    integrations: '集成',
    clients: '客户',
    notifications: '通知',
    modules: '模块',
    solutionTemplates: '解决方案模板',
    widgetsLibrary: '小部件库',
    ruleChains: '规则链',
    whiteLabeling: '白标',
    dashboardBuilder: '仪表板构建器',
    userManagement: '用户管理',
    aiModels: 'AI模型',
    forensicHub: '取证中心',
    smartCityMap: '智慧城市地图',
    droneFusion: '无人机融合',
    cameraHealth: '摄像头健康',
    trafficIntelligence: '交通智能',
    fleetTelematics: '车队/远程信息',
    cybersecurity: '网络安全',
    aiAssistant: 'AI助手',
    settings: '设置',
    profile: '个人资料',
    logout: '登出',
    
    // Common
    save: '保存',
    cancel: '取消',
    delete: '删除',
    edit: '编辑',
    add: '添加',
    search: '搜索',
    filter: '筛选',
    export: '导出',
    import: '导入',
    refresh: '刷新',
    loading: '加载中...',
    noData: '无数据',
    success: '成功',
    error: '错误',
    warning: '警告',
    info: '信息',
    confirm: '确认',
    close: '关闭',
    
    // Solution Templates
    solutionTemplatesTitle: '现成解决方案模板',
    solutionTemplatesDesc: '各行业综合解决方案',
    allCategories: '所有类别',
    security: '安全',
    traffic: '交通',
    retail: '零售',
    industrial: '工业',
    healthcare: '医疗',
    education: '教育',
    preview: '预览',
    deploy: '部署',
    features: '功能',
    requirements: '要求',
    
    // Language
    language: '语言',
    arabic: 'العربية',
    english: 'English',
    french: 'Français',
    spanish: 'Español',
    chinese: '中文',
    selectLanguage: '选择语言',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('app_language');
    return saved || 'ar';
  });

  useEffect(() => {
    localStorage.setItem('app_language', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL, translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export default LanguageProvider;